#Makefile generated by ChatGPT

# Compiler and flags
CC = gcc
CFLAGS = -Wall -g -Wextra -I./utils -I./src
LDFLAGS = -lssl -lcrypto
OBJDIR = ./obj
BINDIR = ./bins

# Source files and their corresponding object files
SRC = $(wildcard ./src/*.c)
OBJ = $(SRC:./src/%.c=$(OBJDIR)/%.o)
DEPS = $(wildcard ./utils/*.h)

# Output executable name
EXEC = $(BINDIR)/rsa

# Default target
all: $(EXEC)

# Create output directories if they don't exist
$(OBJDIR):
	mkdir -p $(OBJDIR)

$(BINDIR):
	mkdir -p $(BINDIR)

# Link the object files to create the executable
$(EXEC): $(OBJ) | $(BINDIR)
	$(CC) $(OBJ) -o $@ $(LDFLAGS)

# Compile source files into object files
$(OBJDIR)/%.o: ./src/%.c | $(OBJDIR)
	$(CC) $(CFLAGS) -c $< -o $@

# Clean up generated files
clean:
	rm -rf $(OBJDIR) $(BINDIR)/$(EXEC)

# Phony targets
.PHONY: all clean
